# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

os: linux
dist: trusty
sudo: required
language: cpp
services:
  - docker

# don't build twice
if: tag IS blank

env:
  global:
    - PLAT=x86_64
    - TRAVIS_TAG=build-8-wheel-linux-cp27mu

before_script:
  - docker pull quay.io/xhochy/arrow_manylinux1_x86_64_base:latest

script:
  - git clone -b master https://github.com/wesm/arrow.git arrow
  - git -C arrow checkout 606799215cae84c029e803645bca8c6a59cb5ef2
  - mkdir -p dist

  # build wheel
  - pushd arrow/python/manylinux1
  - docker run --shm-size=2g
      -e SETUPTOOLS_SCM_PRETEND_VERSION=0.1.dev2853
      -e PYTHON_VERSIONS="2.7,32"
      -e WHEEL_VERSION=0.31.1
      -v $PWD:/io
      -v $PWD/../../:/arrow
      quay.io/xhochy/arrow_manylinux1_x86_64_base:latest /io/build_arrow.sh
  - popd

  # test on multiple distributions
  - docker run -it --shm-size 2G --volume $(pwd)/arrow:/arrow python:2.7-slim
      /arrow/dev/tasks/python-wheels/linux-test.sh

  # prepare for deployment
  - sudo mv arrow/python/manylinux1/dist/* dist/

deploy:
  provider: releases
  api_key: $CROSSBOW_GITHUB_TOKEN
  file_glob: true
  file: dist/*.whl
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    - wesm+git@apache.org